---
- name: Display OS Information
  hosts: all
  gather_facts: false

  tasks:
    - name: Print /etc/os-release
      ansible.builtin.command: cat /etc/os-release
      register: os_info
      changed_when: false

    - name: Display OS Release
      ansible.builtin.debug:
        msg: "{{ os_info.stdout_lines }}"
